export const localeText = {
    page: "Página",
    more: "Mais",
    to: "até",
    of: "de",
    next: "Próximo",
    last: "Último",
    first: "Primeiro",
    previous: "Anterior",
    loadingOoo: "Carregando...",
    selectAll: "Selecionar tudo",
    searchOoo: "Pesquisar...",
    blanks: "(em branco)",
    filterOoo: "Filtrar...",
    applyFilter: "Aplicar filtro...",
    equals: "Igual a",
    notEqual: "Diferente de",
    lessThan: "Menor que",
    greaterThan: "Maior que",
    contains: "Contém",
    notContains: "Não contém",
    startsWith: "Começa com",
    endsWith: "Termina com",
    pageSize: "Tamanho da página",
    sortAscending: "Ordem crescente",
    sortDescending: "Ordem decrescente",
    noSort: "Sem ordenação",
    noRowsToShow: "Nenhum registro encontrado",
};
